on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: linear-kintone-sync
          monorepo-tags: true
          path: packages/lks-core

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version-file: .tool-versions
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        if: ${{ steps.release.outputs['packages/lks-core--release_created'] }}

      - name: Build
        if: ${{ steps.release.outputs['packages/lks-core--release_created'] }}
        run: npm run -w packages/lks-core build

      - name: Publish
        if: ${{ steps.release.outputs['packages/lks-core--release_created'] }}
        run: npm publish -w packages/lks-core --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
